### ISSUE TITLE
How to change the 'collapsed' icon?

### ISSUE THREAD

**Issue by georgio8** [ismyrnow/Leaflet.groupedlayercontrol#35]
I'm using two of these controls and would like them to be distinguished by different icons when collapsed. I have examined the source and can't see where the icon is specified.

I can't see it in the standard Leaflet LayerControl source either – help please!

**Comment by dosstx** [comment]
The icon is a background image in styled via CSS. If you look in the images folder you should see it there.

**Comment by ismyrnow** [comment]
There isn't a way to alter the class name of this control, so you'll have to use more than class names to target one control or the other via CSS.

Here is one way of doing it, which assumes the second layer component is the second component in the div for the top-right area:

```css
.leaflet-control-layers:nth-child(2) .leaflet-control-layers-toggle {
    background: url(http://leafletjs.com/docs/images/leaf-green.png);
}
```
